rename tests to match the files they test
opendp/dp-creator-ii pull request #117
Opened 2024-11-01 01:51 UTC by mccalluc

- Fix #112

2024-11-04 14:47 UTC, ekraffmiller requested changes
This looks good, I just have one more suggestion. Can we have a directory structure under tests that mirrors the source code?  For example have a `tests/utils `and a `tests/utils/templates` for the current test files.  It seems trivial now, but it will make things easier to follow as the code base grows.

2024-11-04 15:46 UTC, mccalluc commented
Sure!

2024-11-04 20:03 UTC, mccalluc commented
Moved some tests down to a `utils` directory. Since
```
.../templates.py
```
is imported the same way as
```
.../templates/__init__py
```
so I think it it best to leave its tests in the util directory: `test__init__.py` would be strange.

2024-11-07 15:15 UTC, ekraffmiller approved these changes

2024-11-07 18:52 UTC, merged